name: stored
description: Dart library for loading data from remote and local sources.
version: 1.0.0
homepage: https://github.com/amondnet/stored/package/stored

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  freezed_annotation: ^0.14.3
  quiver: ^3.0.1
  synchronized:
  rxdart:
dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  freezed: ^0.14.5
  build_runner: ^2.1.1
  coverage: ^1.0.3
