name: Dart CI
on:
  push:
    branches:
      - main
  pull_request: { }
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ stored ]

        sdk: [ stable ]
    defaults:
      run:
        working-directory: package/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: get
        run: |
          dart pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      #- name: Analyze
      #  run: dartanalyzer --fatal-infos --fatal-warnings lib test

      - name: Run tests
        run: |
          dart run gen_coverage
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
          file: package/${{ matrix.package }}/coverage/lcov.info