name: Dart CI
on:
  push:
    branches:
      - main
  pull_request: { }
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ stored ]

        sdk: [ stable ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.12.0
      - name: get
        working-directory: ${{ matrix.package }}
        run: |
          dart pub get

      - name: Format
        working-directory: ${{ matrix.package }}
        run: dart format --set-exit-if-changed .

      - name: Analyze
        working-directory: ${{ matrix.package }}
        run: dartanalyzer --fatal-infos --fatal-warnings lib test

      - name: Run tests
        working-directory: ${{ matrix.package }}
        run: |
          pub run test
          dart test --coverage=coverage
          pub run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
          file: ./${{ matrix.package }}/coverage/lcov.info